### ISSUE TITLE
Ajax搜索报错

### ISSUE THREAD

**Issue by sunxiyuan** [litepress/litepress.cn#109]
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /www/wwwroot/litepress.cn/wp-content/plugins/lava-ajax-search/includes/class.Type.php:54 Stack trace: #0 /www/wwwroot/litepress.cn/wp-content/plugins/lava-ajax-search/includes/class-core.php(436): Lava_Ajax_Search_Type->get_html() #1 /www/wwwroot/litepress.cn/wp-content/plugins/lava-ajax-search/includes/class-core.php(111): Lava_Ajax_Search_Core->do_search() #2 /www/wwwroot/litepress.cn/wp-content/plugins/lava-ajax-search/includes/class-template.php(78): Lava_Ajax_Search_Core->prepare_search_page() #3 /www/wwwroot/litepress.cn/wp-includes/class-wp-hook.php(292): Lava_Ajax_Search_Template->append_search_page() #4 /www/wwwroot/litepress.cn/wp-includes/plugin.php(212): WP_Hook->apply_filters() #5 /www/wwwroot/litepress.cn/wp-includes/post-template.php(253): apply_filters() #6 /www/wwwroot/litepress.cn/wp-content/themes/ui/index.php(24): the_content() #7 /www/wwwroot/litepress.cn/wp-includes/template-loader.php(106): include('...') #8 /www/wwwroot/litepress.cn/wp-blog-header.php(19): require_once('...') #9 /www/wwwroot/litepress.cn/index.php(17): require('...') #10 {main} thrown in /www/wwwroot/litepress.cn/wp-content/plugins/lava-ajax-search/includes/class.Type.php on line 54

**Comment by sunxiyuan** [comment]
问题原因是PHP 8增加了更严格的报错机制，以往数组元素找不到只是一个警告，现在已经成了致命错误了……
