### ISSUE TITLE
cravatar.cn 上传头像失败

### ISSUE THREAD

**Issue by imaegoo** [litepress/litepress.cn#177]
观察控制台 network 发现有 API 报了 500 错误

API：`https://cravatar.cn/wp-admin/admin-ajax.php`
报错：

```
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type WP_Error as array in /www/wwwroot/litepress.cn/wp-content/themes/cravatar/inc/class-upyun.php:36
Stack trace:
#0 /www/wwwroot/litepress.cn/wp-content/themes/cravatar/inc/class-upyun.php(40): LitePress\Cravatar\Inc\Upyun-&gt;send_request()
#1 /www/wwwroot/litepress.cn/wp-content/themes/cravatar/inc/helpers.php(424): LitePress\Cravatar\Inc\Upyun-&gt;post()
#2 /www/wwwroot/litepress.cn/wp-content/themes/cravatar/functions.php(60): LitePress\Cravatar\Inc\purge_avatar_cache()
#3 /www/wwwroot/litepress.cn/wp-includes/class-wp-hook.php(303): {closure}()
#4 /www/wwwroot/litepress.cn/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters()
#5 /www/wwwroot/litepress.cn/wp-includes/plugin.php(470): WP_Hook-&gt;do_action()
#6 /www/wwwroot/litepress.cn/wp-content/plugins/ultimate-member/includes/core/class-uploader.php(493): do_action()
#7 /www/wwwroot/litepress.cn/wp-content/plugins/ultimate-member/includes/core/class-files.php(412): um\core\Uploader-&gt;upload_image()
#8 /www/wwwroot/litepress.cn/wp-includes/class-wp-hook.php(303): um\core\Files-&gt;ajax_image_upload()
#9 /www/wwwroot/litepress.cn/wp-includes/class-wp-hook.php(327): WP_Hook-&gt;apply_filters()
#10 /www/wwwroot/litepress.cn/wp-includes/plugin.php(470): WP_Hook-&gt;do_action()
#11 /www/wwwroot/litepress.cn/wp-admin/admin-ajax.php(187): do_action()
#12 {main}
  thrown in <b>/www/wwwroot/litepress.cn/wp-content/themes/cravatar/inc/class-upyun.php</b> on line <b>36</b><br />
<p>此站点遇到了致命错误。</p><p><a href="https://litepress.cn/support/article/faq-troubleshooting/">了解有关对 LitePress 进行故障排除的更多信息。</a></p>
```

**Comment by sunxiyuan** [comment]
是因为在刷新 CDN 缓存时 HTTP 请求错误导致的，再试一次就好了。
另外已经增加了对该异常的处理逻辑，不会再抛出错误了。

最后，感谢反馈

**Comment by imaegoo** [comment]
谢谢！已成功上传
